// ts-check
import * as falso from "@ngneat/falso";
import {PrismaClient } from "@prisma/client";

const prisma = new PrismaClient()

async function main() {
  await prisma.set.create({
    data: {
      title: "Autogenerated",
      createdBy: {
        create: {
          provider: falso.randWord(),
          providerAccountId: falso.randWord(),
          type: "USER",
          user: {
            create: {
              email: falso.randEmail(),
              name: falso.randFullName()
            },
          },
        },
      },
      terms: {
        create: [...Array(50)].map(() => {
          return {
            term: falso.randWord(),
            definition: falso.randWord(),
          };
        }),
      },
    },
  });
}
main();
export { main };
