// ts-check
import * as falso from "@ngneat/falso";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  for (let i = 0; i < 20; i++) {
    await prisma.set.create({
      data: {
        title: `Autogenerated number ${i}`,
        createdBy: {
          create: {
            provider: falso.randWord(),
            providerAccountId: falso.randWord(),
            type: "USER",
            user: {
              connectOrCreate: {
                where: { id: "auto-user" },
                create: { email: falso.randEmail(), name: falso.randFullName(), id: "auto-user" },
              },
            },
          },
        },
        terms: {
          create: [...Array(50)].map(() => {
            return {
              term: falso.randWord(),
              definition: falso.randWord(),
            };
          }),
        },
      },
    });
  }
}
main();
export { main };
